#!/bin/bash -ex

INTERFACE="wlp2s0"

DHCPCD_PID="$(< /run/dhcpcd-${INTERFACE}.pid)"
test -n "${DHCPCD_PID}" && sudo kill "${DHCPCD_PID}"
sudo iw dev "${INTERFACE}" disconnect
sudo ip link set "${INTERFACE}" down
wlan-disable
